spring:
  jackson:
    time-zone: America/Cuiaba
    date-format: yyyy-MM-dd
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
    url: jdbc:postgresql://77.37.40.105:5432/meubanco?currentSchema=gestor_servidor

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 300000
    refresh-token:
      expiration-time: 604800000

server:
  servlet:
    context-path: /seplag-api